### ISSUE TITLE
connection problem with v1.3 (worked in v1.2)

### ISSUE THREAD

**Issue by cavebeat** [gsantner/cherrymusic-android#6]
#### General information

Tested with two devices, same behaviour on both. 

* **Device:** eg Nexus 7
* **Android Version:**  CyanogenMOD 12.1, Android 5.1.1
* **App source:** F-Droid
* **App version:** 1.2.0 and 1.3.0

* **Device:** Samsung Galaxy S2 
* **Android Version:** CM13.0, Android 6.0.1
* **App source:** F-Droid
* **App version:** 1.2.0, vs 1.3.0

I have:
- [X] searched open and closed issues for duplicates (cherrymusic and cherrymusic-android)
- [ ] read <https://github.com/gsantner/cherrymusic-android/blob/master/CONTRIBUTING.md>
Link is Dead

#### Steps to reproduce

Tried with Browser(Firefox) directly. The Cherrymusic instance is running in my Lan with path /cherry. http://192.168.1.2:8080/cherry 
It is also published with an Reverse Proxy (Apache vHost subdomain) at https://cherry.mydomain.tld/cherry . The SSL Certificate for the subdomain is valid and expires in > 1 month. 
Both are showing the same cherrymusic instance with 0.40.0+devel-1-g3d533b3 and do not show any signs of a problem in the browser. 

So both paths should be reachable. The LAN Instance directly from LAN. The SSL instance from everywhere on the internet. 

Test 1:
1. Install App Version 1.3.0
2. Settings set Path to https://cherry.mydomain.tld/cherry, user example, pw trustno1
3. Try to connect, Fail. Get "404 Not Found - The path '/cherry/index.php' was not found."
4. Install App Version 1.2.0
5. Try to Connect, Works

Test 2:
1. Install App Version 1.3.0
2. Settings set Path to http://192.168.1.2:8080/cherry, user example, pw trustno1
5. Try to Connect, Works
4. Install App Version 1.2.0
5. Try to Connect, Works

#### Expected result

With v1.3.0 i receive a Get "404 Not Found - The path '/cherry/index.php' was not found." HTTP Error Code

#### Debug output

no debuging done

**Comment by gsantner** [comment]
Hey there,
I setted up a fresh installation of cherrymusic and fresh installed the app. Sorry, but I cannot reproduce your problem.

I tried 

* cherrymusic config: `rootpath = /`  ; app: `http://ip:port/`
* cherrymusic config: `rootpath = /cherry/`  ; app: `http://ip:port/cherry`

and both do work in my case. Do you use some kind of frontsever (apache/nginx) for serving via reverseproxy? The app doesn't use `index.php` in any way, this seems to come from some kind of `Index` config options of e.g. your Apache config.
