### ISSUE TITLE
WebView content lost after device rotation

### ISSUE THREAD

**Issue by calbee633810** [gsantner/cherrymusic-android#7]
#### General information

* **Device:** Nexus 4 emulator
* **Android Version:** android 23
* **App source:**  F-Droid
* **App version:** 1.2.0

I have:
- [ ] searched open and closed issues for duplicates
- [ ] read <https://github.com/gsantner/cherrymusic-android/blob/master/CONTRIBUTING.md>

#### Steps to reproduce

1. open app
2. rotate screen twice

#### Expected result
The red ball at the right bottom part of the screen should still be there

What is the expected output? What do you see instead?
However, it disappears and I can do nothing with the app.

![screen shot 2018-04-12 at 9 45 42 pm](https://user-images.githubusercontent.com/38213896/38681524-7bb6871e-3e9b-11e8-96dd-b05072119d94.png)
Screenshot before rotation

![screen shot 2018-04-12 at 9 45 32 pm](https://user-images.githubusercontent.com/38213896/38681531-808ddba2-3e9b-11e8-948c-00463b3da7c4.png)
Screenshot after the first rotation

![screen shot 2018-04-12 at 9 45 42 pm](https://user-images.githubusercontent.com/38213896/38681554-8aea21d2-3e9b-11e8-8bc2-ffcb11432be0.png)
Screenshot after the second rotation

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Cherry and include all the steps it takes to reproduce the problem.

````
adb logcat -s de.live.gdev.cherrymusic
````

**Comment by gsantner** [comment]
Good catch! Having always rotation lock on so didn't quite get that yet.

Happy about PRs ;)
